# add your settings here (overriding the defaults)

biocypher:
  offline: true
  debug: false
  schema_config_path: config/schema_config.yaml

  head_ontology: 
    url: http://semanticweb.cs.vu.nl/2009/11/sem/
    root_node: Core
    format: rdf

neo4j:
  delimiter: '\t'
  array_delimiter: '|'
  quote_character: '+'
  skip_duplicate_nodes: true
  skip_bad_relationships: true
