# add your settings here (overriding the defaults)

biocypher:
  offline: true
  debug: false
  schema_config_path: config/schema_config_vhp.yaml

  head_ontology:
      url: https://github.com/biolink/biolink-model/raw/v3.2.1/biolink-model.owl.ttl
      root_node: entity

neo4j:
  delimiter: '\t'
  array_delimiter: "|"
  quote_character: "+"
  skip_duplicate_nodes: true
  skip_bad_relationships: true
