# add your settings here (overriding the defaults)

biocypher:
  offline: true
  debug: false
  schema_config_path: config/schema_config_vhp.yaml

  head_ontology:
      url: https://raw.githubusercontent.com/biolink/biolink-model/refs/tags/v4.2.2/project/owl/biolink_model.owl.ttl
      root_node: entity

neo4j:
  delimiter: '\t'
  array_delimiter: "|"
  quote_character: "+"
  skip_duplicate_nodes: true
  skip_bad_relationships: true
